name: Publish
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "22.x"
      - run: pnpm i
      - run: pnpm run build
      - run: |
          echo @snorlaxkaran:https://npm.pkg.github.com/ > dist/.npmrc
          echo '//npm.pkg.github.com/:_authToken=${NPM_HELPER_TOKEN}' >> dist/.npmrc
      - run: pnpm publish
        working-directory: ./dist
        env:
          NPM_HELPER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
